package io.github.remmerw.nott


internal object Names {
    const val ID: String = "id"
    const val A: String = "a"
    const val INFO_HASH: String = "info_hash"
    const val PORT: String = "port"
    const val TOKEN: String = "token"
    const val NODES: String = "nodes"
    const val NODES6: String = "nodes6"
    const val R: String = "r"
    const val T: String = "t"
    const val Y: String = "y"
    const val Q: String = "q"
    const val E: String = "e"
    const val V: String = "v"
    const val IP: String = "ip"
    const val RO: String = "ro"
    const val NAME: String = "name"
    const val TARGET: String = "target"
    const val VALUES: String = "values"
    const val ANNOUNCE_PEER: String = "announce_peer"
    const val PING: String = "ping"
    const val PUT: String = "put"
    const val FIND_NODE: String = "find_node"
    const val GET_PEERS: String = "get_peers"
    const val GET: String = "get"
    const val CAS: String = "cas"
    const val SEQ: String = "seq"
    const val SIG: String = "sig"
    const val K: String = "k"
    const val SALT: String = "salt"

}